### ISSUE TITLE
PowerShell ISE not supported

### ISSUE THREAD

**Issue by petegrimsdale** [Azure/arm-template-whatif#35]
**Describe the bug**

**To Reproduce**
Run the WhatIf module in Powershell ISE

Lables for Delete / modify / create are not displayed correctly (see screenshot)

**Expected behavior**
Powershell ISE to support the WhatIf module in the same way as Powershell

**Screenshots**
![whatif_ise](https://user-images.githubusercontent.com/46575174/74547701-71923880-4f44-11ea-90b7-f4b425b71e84.png)

**Client**
PowerShell ISE

**Additional context**

**Comment by alex-frankel** [comment]
I don't think we are going to support powershell ISE. We are only targeting powershell core, and from what I understand PowerShell ISE was not designed to support powershell core (6+).

Will wait for @shenglol to confirm and then will likely close this.

**Comment by shenglol** [comment]
I’ll investigate into this.

**Comment by shenglol** [comment]
@alex-frankel I did some research and can confirm that PowerShell ISE could not be supported - it is a WPF app but not a console-based app. What you see with its Command tool window is an emulation of console mode but not a 100% fool proof emulation. That's why the raw ANSI escape sequences got printed out instead of being interpreted.

@petegrimsdale If you want to use the cmdlet in an interactive editing environment, an alternative would be the [VSCode PowerShell extension](https://code.visualstudio.com/docs/languages/powershell), which uses the VSCode integrated terminal that supports true color.
